{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Sheet1\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1452.0 (24.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-AU",
    "cultures": [
      {
        "name": "en-AU",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-AU",
    "tables": [
      {
        "name": "Sheet1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Service Pathways",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e7e02d5-cf6d-4b64-ab80-0e56dffde569",
            "sourceColumn": "Service Pathways",
            "summarizeBy": "none"
          },
          {
            "name": "Major Funder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "009a56d6-de5a-4d51-a0bd-52e47781b1ac",
            "sourceColumn": "Major Funder",
            "summarizeBy": "none"
          },
          {
            "name": "Provider",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb1d9687-8af1-4cc5-aafa-02aa9fe5d28c",
            "sourceColumn": "Provider",
            "summarizeBy": "none"
          },
          {
            "name": "Service Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e0a6ed6-65d7-42de-8c5c-1cc79c1c0065",
            "sourceColumn": "Service Type",
            "summarizeBy": "none"
          },
          {
            "name": "Service Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24501b87-7280-40bd-a310-018918fb380f",
            "sourceColumn": "Service Sector",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7ae093eb-2307-488a-a590-2aa68ac7f9aa",
        "partitions": [
          {
            "name": "Sheet1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"R:\\DVAVETSUIC-I3277\\Maddy\\Framework Review\\Service Pathway table.xlsx\"), null, true),",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Sheet1_Sheet,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Column1\", \"Major Funder\"}, {\"Column2\", \"Provider\"}, {\"Column3\", \"Service Type\"}, {\"Column4\", \"Service Sector\"}}),",
                "    #\"Removed Top Rows\" = Table.Skip(#\"Renamed Columns\",1),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Top Rows\", each true),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Filtered Rows\",{{\"Service Type\", \"Provider\"}, {\"Column5\", \"Service Sector\"}, {\"Service Sector\", \"Service Type\"}, {\"Major Funder\", \"Service Pathways\"}, {\"Provider\", \"Major Funder\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}